Matrix:
  AvatarRef:
    - !imageFile C:\Users\waldemar\Dropbox\Bilder\Fertiges\Avatars\cosplay2018.jpg
    - !imageFile C:\Users\waldemar\Dropbox\Bilder\Fertiges\Avatars\DarkLink.png
  FlagRef:
    #- !imageFile C:\Users\waldemar\Dropbox\Bilder\Materialien\PrideProgress.png
    #- !imageUrl https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Nonbinary_flag.svg/1200px-Nonbinary_flag.svg.png
    - !imagePipeline
      Instance:
        Pipeline: !textFile ../../../../Demo/blank.pipeline.csx
        Configuration:
            Red: 255
            Green: 128
            Blue: 255
      Publish: result
Configuration:
  Radius: 0.9
  CirclePoints: 50
